### ISSUE TITLE
Add Graphviz to Markdown renderer

### ISSUE THREAD

**Issue by finanalyst** [finanalyst/rakuast-rakudoc-render#12]
Graphviz is so useful, it should be available for Markdown files as well as HTML.

**Comment by banjaminlee** [comment]
https://bold.pro/my/banjamin-lee-241212153841

This is my resume.
I want to work for you.
I look forward your reply.

**Comment by finanalyst** [comment]
completed

**Comment by jubilatious1** [comment]
Hi @finanalyst, I'm going to add `Gephi` here, if you need a Graphviz viewer (and don't know about it already):

https://gephi.org
